name: Deploy Node.js Function to Azure Function App - ai-email-function

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install function dependencies
        run: |
          cd backend/dailyEmail
          npm install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: backend/dailyEmail/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.function-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: backend/dailyEmail/
      - name: Deploy to Azure Function App
        id: deploy-to-function
        uses: azure/functions-action@v1
        with:
          app-name: 'ai-email-function'
          package: backend/dailyEmail/
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
